apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-bench
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-bench
rules:
- apiGroups: [""]
  resources:
  - pods
  - nodes
  - services
  - configmaps
  - secrets
  - endpoints
  - serviceaccounts
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
  - pods/log
  verbs: ["get"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "delete", "create"]
- apiGroups: ["operator.openshift.io"]
  resources:
  - kubeapiservers
  - openshiftapiservers
  verbs: ["get", "list"]
- apiGroups: ["config.openshift.io"]
  resources:
  - clusteroperators
  - clusterversions
  verbs: ["get", "list"]
- apiGroups: ["security.openshift.io"]
  resources:
  - securitycontextconstraints
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["get", "list"]
- apiGroups: ["policy"]
  resources:
  - podsecuritypolicies
  verbs: ["get", "list"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - networkpolicies
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-bench
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-bench
subjects:
- kind: ServiceAccount
  name: kube-bench
  namespace: default
