apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: resolve
spec:
  params:
    - name: imagestream-name
      type: string
    - name: imagestream-tag
      type: string
      default: latest
  results:
    - name: image-ref
      description: Image reference resolved from ImageStream
  steps:
    - name: get-image-ref
      image: quay.io/openshift/origin-cli:4.13
      script: |
        #!/bin/sh
        set -e
        IMAGE=$(oc get is $(params.imagestream-name) \
          -o jsonpath="{.status.tags[?(@.tag=='$(params.imagestream-tag)')].items[0].dockerImageReference}")
        echo -n "$IMAGE" > "$(results.image-ref.path)"
        echo "results = $(results.image-ref.path)"
        echo "[INFO] Resolved image: $IMAGE"