apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: vulnado-build-and-scan
spec:
  workspaces:
    - name: source
      description: The workspace containing the source code.
  params:
    - name: buildconfig-name
      default: vulnado-build-config
    - name: imagestream-name
      default: vulnado-image-stream
    - name: imagestream-tag
      default: latest
  results:
    - name: image-ref
      description: The built image reference.
  steps:
    - name: start-build
      image: quay.io/openshift/origin-cli:4.13
      script: |
        #!/bin/sh
        echo "Starting OpenShift build..."
        oc start-build $(params.buildconfig-name) --follow
        IMAGE=$(oc get is $(params.imagestream-name) \
          -o jsonpath="{.status.tags[?(@.tag=='$(params.imagestream-tag)')].items[0].dockerImageReference}")
        echo -n "$IMAGE" > "$(results.image-ref.path)"
        echo "results = $(results.image-ref.path)"
        echo "[INFO] Resolved image: $IMAGE"