apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: appsec-pipeline
spec:
  description: |
    Pipeline that automates security
  params:
    - name: repo-url
      type: string
      description: The Git repository URL.
    - name: revision
      type: string
      description: Optional git revision (branch, tag, or commit).
      default: "master"
    - name: iq-server-url
      type: string
      description: The URL of the Sonatype Nexus IQ Server.
      default: "http://34.18.141.239:8070/"
    - name: iq-application-id
      type: string
      description: The application ID in Nexus IQ Server.
      default: "1"
    - name: sonatype-auth-secret
      type: string
      description: The name of the Kubernetes secret containing Sonatype credentials.
      default: "sca-credentials"
    - name: ssc-url
      type: string
      description: The URL of the Fortify Software Security Center (SSC) server.
    - name: ssc-application-id
      type: string
      description: The application ID in SSC.
    - name: sensor-version
      type: string
      description: The version of the Fortify SAST sensor to use.
      default: "25.2"
    - name: ssc-auth-secret
      type: string
      description: The name of the Kubernetes secret containing SSC credentials.
      default: "ssc-credentials"
    - name: client-auth-token-secret
      type: string
      description: The name of the Kubernetes secret containing Client Auth Token credentials.
      default: "client-auth-token-secret"
    - name: run-sast-scan
      type: string
      description: Flag to determine whether to run the SAST scan.
      default: "true"
    - name: run-sca-scan
      type: string
      description: Flag to determine whether to run the SAST scan.
      default: "true"
    - name: run-build
      type: string
      description: Flag to determine whether to run the SAST scan.
      default: "true"
    - name: run-docker-1
      type: string
      description: Flag to determine whether to run the Docker 1.4 scan.
      default: "false"
    - name: run-docker-2
      type: string
      description: Flag to determine whether to run the Docker 2.0 scan.
      default: "true"
    - name: run-hadolint-scan
      type: string
      description: Flag to determine whether to run the Hadolint scan.
      default: "true"
    - name: run-trivy-scan
      type: string
      description: Flag to determine whether to run the Trivy image scan.
      default: "true"
    - name: run-kube-bench
      type: string
      description: Flag to determine whether to run the kube-bench CIS Kubernetes benchmark scan.
      default: "false"
    - name: run-dast-scan
      type: string
      description: Flag to determine whether to run the DAST scan.
      default: "true"
    - name: run-anchore-scan
      type: string
      description: Flag to determine whether to run the Anchore image scan.
      default: "true"
    - name: target-url
      type: string
      description: The target URL to scan
    - name: scan-name
      type: string
      description: The name for the DAST scan
      default: "Pipeline-DAST-Scan"
    - name: scan-settings-id
      type: string
      description: The scan settings CI/CD token or ID
      default: "ssc-credentials"
    - name: scan-mode
      type: string
      description: Scan mode (CrawlOnly, CrawlAndAudit, AuditOnly)
      default: "CrawlAndAudit"
    - name: manifest-repo-url
      type: string
      description: The Git repository URL for manifests.
      default: "https://github.com/BRHM1/openshift-manifests.git"
    - name: run
      type: array
      description: List of Tasks to run
      default: ["git-clone", "build-docker-image", "update-image-tag", "dast-scan"]
  workspaces:
    - name: shared-data
      description: Workspace for the cloned repo.
  tasks:
    - name: git-clone
      displayName: "Checkout Source Code"
      taskRef:
        name: git-clone
      serviceAccountName: tekton-build-sa
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: build
      displayName: "Build Application"
      taskRef:
        name: build
      when:
        - input: "build"
          operator: in
          values: ["$(params.run[*])"]
      serviceAccountName: tekton-build-sa
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: shared-data
    - name: sonatype-scan
      displayName: "Sonatype SCA Scan"
      taskRef:
        name: sonatype-scan
      runAfter:
        - build
      when:
        - input: "sonatype-scan"
          operator: in
          values: ["$(params.run[*])"]
      workspaces:
        - name: source
          workspace: shared-data
        - name: reports
          workspace: shared-data
      params:
        - name: iq-server-url
          value: $(params.iq-server-url)
        - name: iq-application-id
          value: $(params.iq-application-id)
        - name: sonatype-auth-secret
          value: $(params.sonatype-auth-secret)
    - name: sast-scan
      displayName: "SAST Scan"
      taskRef:
        name: sast
      runAfter: 
        - sonatype-scan
      when:
        - input: "sast-scan"
          operator: in
          values: ["$(params.run[*])"]
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: ssc-url
          value: $(params.ssc-url)
        - name: ssc-application-id
          value: $(params.ssc-application-id)
        - name: sensor-version
          value: $(params.sensor-version)
        - name: ssc-auth-secret
          value: $(params.ssc-auth-secret)
        - name: client-auth-token-secret
          value: $(params.client-auth-token-secret)
    - name: hadolint-scan
      displayName: "Dockerfile Scan - Hadolint"
      taskRef:
        name: hadolint-scan
      workspaces:
        - name: source
          workspace: shared-data
      when:
        - input: "hadolint-scan"
          operator: in
          values: ["$(params.run[*])"]
      runAfter:
        - sast-scan
    - name: build-docker-image
      displayName: "Build Docker Image - OpenShift Workflow"
      taskRef:
        name: build-docker-image
      runAfter:
        - hadolint-scan
      when:
        - input: "build-docker-image"
          operator: in
          values: ["$(params.run[*])"]
      serviceAccountName: image-builder-sa
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: buildconfig-name
          value: build-config
        - name: imagestream-name
          value: image-stream
        - name: imagestream-tag
          value: latest
    - name: trivy-image-scan
      displayName: "Trivy Image Scan"
      taskRef:
        name: trivy-image-scan
      workspaces:
        - name: scan-data
          workspace: shared-data
      runAfter:
        - build-docker-image
      when:
        - input: "trivy-image-scan"
          operator: in
          values: ["$(params.run[*])"]
      params:
        - name: image-ref
          value: "$(tasks.build-docker-image.results.image-ref)"
        - name: exit-on-critical
          value: "false"
    - name: anchore-scan
      displayName: "Anchore Image Scan"
      taskRef:
        name: anchore-scan
      when:
        - input: "anchore-scan"
          operator: in
          values: ["$(params.run[*])"] 
      runAfter:
        - build-docker-image
      params:
        - name: image
          value: "$(tasks.build-docker-image.results.image-ref)"
    - name: kube-bench
      displayName: "CIS Kubernetes Benchmark Scan"
      taskRef:
        name: kube-bench
      when:
        - input: "kube-bench"
          operator: in
          values: ["$(params.run[*])"]
      runAfter:
        - anchore-scan
      params:
        - name: benchmark
          value: "rh-1.0"
        - name: image
          value: "docker.io/aquasec/kube-bench:v0.13.0-ubi-fips"
    - name: update-image-tag
      displayName: "Update Image Tag in Git"
      taskRef:
        name: k8s-update-image-tag
      runAfter:
        - kube-bench
      workspaces:
        - name: source
          workspace: shared-data
      when: 
        - input: "update-image-tag"
          operator: in
          values: ["$(params.run[*])"]
      params:
        - name: git-repo-url
          value: "$(params.manifest-repo-url)"
        - name: git-branch
          value: "main"
        - name: git-credentials-secret
          value: "git-credentials"
        - name: image-tag
          value: "$(tasks.build-docker-image.results.image-ref)"
        - name: build-id
          value: "$(context.pipelineRun.name)"
    - name: dast-scan
      displayName: "DAST Scan"
      taskRef:
        name: dast
      when:
        - input: "dast-scan"
          operator: in
          values: ["$(params.run[*])"]
      runAfter:
        - update-image-tag
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: target-url
          value: $(params.target-url)
        - name: scan-name
          value: $(params.scan-name)
        - name: scan-settings-id
          value: $(params.scan-settings-id)
        - name: ssc-url
          value: $(params.ssc-url)
        - name: ssc-auth-secret
          value: $(params.ssc-auth-secret)
        - name: scan-mode
          value: $(params.scan-mode)

















